// GENERATED — tokens.css + panel.css concatenated by scripts/sync-css.mjs.
// The panel carries its own styles (and its own tokens) so a host needs no
// separate import. Kept as a plain string constant (no CSS import) so the
// tsup library build stays clean. Edit app/panel.css or design/tokens.json,
// then run scripts/sync-css.mjs to re-sync (manual copies drift — this one did).
export const PANEL_CSS = String.raw`
/* GENERATED from design/tokens.json by scripts/gen-tokens.mjs — DO NOT EDIT */
:root {
  --bg: #06080e;
  --bg-lift: #0a0d15;
  --card: #0f131c;
  --line: #1c2130;
  --line-hi: #2b3243;
  --text: #E8DCC4;
  --dim: #8a8268;
  --faint: #585240;
  --gold: #c9a04a;
  --gold-hi: #E8C877;
  --teal: #4ECDC4;
  --violet: #a78bd0;
  --green: #5fae7e;
  --amber: #d6a23e;
  --red: #d05a5a;
  --wine: #0b0509;
  --wine2: #140a11;
  --plate: #1c1119;
  --plate-lift: #241624;
  --brass: #d9a05b;
  --brass-hi: #efc389;
  --brass-deep: #a9753a;
  --mint: #8be9b0;
  --cream: #f4eee2;
  --cream-dim: #b3a897;
  --cream-faint: #7c7365;
  --verb-reports-to: #c9a04a;
  --verb-declares: #E8C877;
  --verb-amends: #E8C877;
  --verb-inherits: #8a8268;
  --verb-owns: #4ECDC4;
  --verb-reads: #3a7a74;
  --verb-escalates-to: #d05a5a;
  --verb-covers: #5fae7e;
  --verb-supplies: #a8815a;
  --verb-audits: #a78bd0;
  --verb-spine: #29242f;
  --display: Fraunces, ui-serif, Georgia, serif;
  --ui: 'DM Sans', ui-sans-serif, system-ui, sans-serif;
  --mono: 'JetBrains Mono', ui-monospace, SFMono-Regular, monospace;
  --ease-swift: cubic-bezier(0.2, 0.7, 0.25, 1);
  --ease-settle: cubic-bezier(0.16, 1, 0.3, 1);
  --z-canvas: 0;
  --z-hud: 10;
  --z-dossier: 20;
  --z-palette: 30;
  --z-toast: 40;
}

/* Booboo Organigram — alive, simple, for everyone. One accent (verdigris,
   the dachshund's collar), a slow aurora breathing behind everything, cards
   that lift and settle, numbers that count up. Dark by default. */

:root {
  /* THE STAFF BOARD — a master-key rack, not a dashboard.
     Structure comes from two real artefacts: a master-key hierarchy (passe
     général → passe partiel → cylinder, which is literally how a hotel is
     keyed, and exactly how authority cascades here) and a ministry organigram
     (rank is NAMED in column headers, never inferred from indentation).
     Material comes from the approved FHQ hero designs — wine-black ground,
     brass rails, real vendor marks on white chips.
     Raw values are generated into app/tokens.css from design/tokens.json
     (scripts/gen-tokens.mjs); these are the panel's semantic aliases over them.
     RANK READS THROUGH FINISH, NEVER HUE. The old board coloured each card by
     hash(agent.id) — nine departments, nine arbitrary neon hues — which is the
     loudest "generated by a dev tool" signal there is, and it disagreed with
     the cosmos's own gold/silver/bronze ladder. */
  /* LIGHT IS THE DEFAULT (Jesse, 2026-07-19: "design for everyone — a white
     background, very light bubbles, beautiful refined display"). A whole hotel
     uses this, not a room of developers; a stranger should not land in a
     terminal. Dark remains, one toggle away, below.
     The ground is a WARM white, never flat #fff — a lit room, not a sheet of
     paper. Depth comes from layered shadow, so ink stays the only dark thing
     on screen and brass drops from material to ~5% accent. */
  --bg: #fcfbf9;
  --bg-1: #fffefb;      /* tinted toward the brass hue, never flat #fff */
  --bg-2: #f6f4f0;
  --line: #e9e5df;
  --line-soft: #f0ece6;
  --line-2: #d9d3c9;
  --surface-tray: rgba(255, 255, 255, .5);
  /* the ground-plane dot. White-on-white rendered NOTHING on the light board
     — the texture was there in the stylesheet and absent on screen. */
  --dot: rgba(27, 24, 21, 0.055);
  --surface-lift: linear-gradient(180deg, #fffdf8, #ffffff);
  --surface-lift-edge: #e8d9bd;
  --ink: #1b1815;
  --ink-2: #6b6459;
  --ink-3: #9a9287;
  --accent: #a9753a;
  --accent-2: #c9954f;
  --accent-dim: #f7f0e4;
  --warn: #b8862c;
  --warn-wash: #fbf3e3;
  --ok: #3f9c6d;
  --ok-wash: #eaf5ef;
  --fail: #c0553f;
  --fail-wash: #fbeeea;
  /* one shadow set, three depths — the only source of elevation */
  --sh-1: 0 1px 2px rgba(27, 24, 21, .04), 0 1px 1px rgba(27, 24, 21, .03);
  --sh-2: 0 2px 4px rgba(27, 24, 21, .04), 0 6px 16px -6px rgba(27, 24, 21, .10);
  --sh-3: 0 4px 8px rgba(27, 24, 21, .05), 0 16px 34px -12px rgba(27, 24, 21, .16);
  /* motion — slight, never showy. Everything eases on these two. */
  --ease: cubic-bezier(.2, .7, .25, 1);
  --settle: cubic-bezier(.16, 1, .3, 1);
  --font: "DM Sans", -apple-system, "Segoe UI", Inter, system-ui, sans-serif;
  --mono: "JetBrains Mono", ui-monospace, "SF Mono", Menlo, monospace;
  --display: "Fraunces", ui-serif, Georgia, serif;
  --brass-line: linear-gradient(180deg, var(--brass-hi), var(--brass) 55%, var(--brass-deep));
}

/* DARK — the wine-and-brass board, now one toggle away instead of the default.
   Same structure, same shadows-as-depth logic, inverted ground. */
:root[data-theme="dark"] {
  --bg: var(--wine);
  --bg-1: var(--plate);
  --bg-2: var(--wine2);
  --line: rgba(244, 238, 226, 0.13);
  --line-soft: rgba(244, 238, 226, 0.08);
  --line-2: rgba(244, 238, 226, 0.22);
  --surface-tray: rgba(11, 5, 9, .4);
  --dot: rgba(255, 255, 255, 0.035);
  --surface-lift: linear-gradient(168deg, #3a2a16, #1d1410);
  --surface-lift-edge: rgba(239, 195, 137, .4);
  --ink: var(--cream);
  --ink-2: var(--cream-dim);
  --ink-3: var(--cream-faint);
  --accent: var(--brass);
  --accent-2: var(--brass-hi);
  --accent-dim: rgba(217, 160, 91, 0.12);
  --warn: var(--brass);
  --warn-wash: rgba(217, 160, 91, 0.10);
  --ok: var(--mint);
  --ok-wash: rgba(139, 233, 176, 0.10);
  --fail: #e07b6a;
  --fail-wash: rgba(224, 123, 106, 0.10);
  --sh-1: 0 1px 2px rgba(0, 0, 0, .5);
  --sh-2: 0 2px 4px rgba(0, 0, 0, .5), 0 16px 34px -18px rgba(0, 0, 0, .85);
  --sh-3: 0 4px 8px rgba(0, 0, 0, .5), 0 22px 48px -18px rgba(0, 0, 0, .9);
}
[data-theme="dark"] body { background: var(--wine); }
[data-theme="dark"] .ag { background: linear-gradient(168deg, var(--plate-lift), #180e16); }
[data-theme="dark"] .bar, [data-theme="dark"] .tabs { background: rgba(11, 5, 9, 0.72); }
[data-theme="dark"] .rack .wt { background: #fff; border-color: transparent; }
[data-theme="dark"] .pnl-stars { opacity: .45; }

* { box-sizing: border-box; }
body { font-family: var(--font); color: var(--ink); background: var(--bg); overflow-x: hidden; }

.pnl { display: flex; flex-direction: column; position: relative; overflow: hidden; }

/* the ground — warm wine light pooling from the top-left, exactly as the hero
   grades it. NO GRAIN/NOISE LAYER: the mockup carried a feTurbulence overlay
   and it read as a blurry filter smeared over everything (Jesse, 2026-07-19).
   The atmosphere is gradient + constellation only. */
.pnl-aurora {
  position: fixed; inset: -30%; pointer-events: none; z-index: 0; opacity: 1;
  background:
    radial-gradient(55% 45% at 12% 0%, rgba(201, 149, 79, .055), transparent 62%),
    radial-gradient(45% 40% at 95% 100%, rgba(63, 156, 109, .035), transparent 62%);
  animation: aurora 48s ease-in-out infinite alternate;
}
@keyframes aurora {
  0% { transform: translate(0, 0) scale(1); }
  50% { transform: translate(3%, -2%) scale(1.06); }
  100% { transform: translate(-3%, 2%) scale(1.02); }
}
@media (prefers-reduced-motion: reduce) {
  /* everything lands at its final state — honest for users, crisp for captures */
  .pnl-aurora, .ag.root::before, .ag.root::after, .ag, .content, .bk-card, .tl-row, .mem-row,
  .rule-card, .doss, .doss-rep, .bar-draft, .ag-light.fail, .mac-dot.fail { animation: none !important; }
}
/* the fit is a TRANSITION not an animation — suppress it explicitly so the org
   snaps to its fitted size instantly under reduced-motion (honest for captures) */
@media (prefers-reduced-motion: reduce) { .chart { transition: none !important; } }

/* top bar */
.bar {
  position: relative; z-index: 2; display: flex; align-items: center; gap: 22px;
  padding: 14px 26px; border-bottom: 1px solid var(--line-soft);
  background: rgba(252, 251, 249, 0.82); backdrop-filter: blur(10px);
  flex-wrap: wrap;
}
.bar-brand { font-size: 19px; font-family: var(--display); font-weight: 600; letter-spacing: -0.01em; }
.bar-brand b { font-weight: 600; color: var(--accent-2); }
.bar-stats { display: flex; gap: 18px; color: var(--ink-2); font-size: 12.5px; }
.bar-stats b { color: var(--ink); font-variant-numeric: tabular-nums; font-size: 14px; }
.bar-stats .tap { cursor: pointer; transition: color 0.15s; }
.bar-stats .tap:hover { color: var(--accent); }
.bar-stats .tap:hover b { color: var(--accent); }
.bar-actions { margin-left: auto; display: flex; align-items: center; gap: 10px; }
.bar-ok { color: var(--accent); font-size: 12px; }
.bar-draft { color: var(--warn); font-size: 12px; animation: pulse 1.6s ease-in-out infinite; }
@keyframes pulse { 0%, 100% { opacity: 1; } 50% { opacity: 0.5; } }

.btn {
  border: 1px solid var(--line); background: var(--bg-2); color: var(--ink);
  border-radius: 9px; padding: 8px 15px; font-size: 12.5px; cursor: pointer;
  transition: border-color .18s var(--ease), transform .12s var(--ease), box-shadow .2s var(--ease);
}
.btn:hover { border-color: var(--accent); }
.btn:active { transform: scale(0.97); }
.btn.primary { background: var(--accent); border-color: var(--accent); color: #fff; font-weight: 650; }
.btn.primary:disabled { opacity: 0.5; cursor: wait; }
.btn.ghost { background: transparent; color: var(--ink-2); }

/* tabs */
.tabs {
  position: relative; z-index: 2; display: flex; gap: 4px; padding: 0 22px;
  border-bottom: 1px solid var(--line); background: rgba(252, 251, 249, 0.7); backdrop-filter: blur(8px);
  overflow-x: auto;
}
.tab {
  background: none; border: none; border-bottom: 2px solid transparent; color: var(--ink-2);
  transition: color .18s var(--ease), border-color .22s var(--ease);
  font-size: 12.5px; padding: 12px 15px 11px; cursor: pointer; white-space: nowrap;
  transition: color 0.15s, border-color 0.2s;
}
.tab:hover { color: var(--ink); }
.tab.on { color: var(--accent); border-bottom-color: var(--accent); font-weight: 600; }
.tab-glyph { margin-right: 5px; opacity: 0.85; }

/* every tab's content rises in — the key on .content retriggers it */
.content { position: relative; z-index: 1; flex: 1; display: flex; flex-direction: column; min-height: 0; animation: rise 0.28s ease both; }
@keyframes rise { from { opacity: 0; transform: translateY(8px); } to { opacity: 1; transform: none; } }

.screen { flex: 1; overflow-y: auto; padding: 30px 34px 60px; max-width: 900px; }
.scr-title { display: flex; align-items: center; gap: 10px; font-size: 20px; margin: 0 0 6px; }
.scr-count { font-size: 12px; background: var(--accent-dim); color: var(--accent); border-radius: 99px; padding: 3px 10px; font-variant-numeric: tabular-nums; }
.scr-sub { color: var(--ink-2); font-size: 12.5px; margin: 0 0 24px; }
.scr-empty { color: var(--ink-3); font-size: 13px; line-height: 1.6; }
.scr-empty code, .scr-sub code { font-family: var(--mono); background: var(--bg-2); padding: 1px 6px; border-radius: 5px; font-size: 11.5px; }
.pnl-back { background: none; border: 1px solid var(--line); color: var(--ink-2); border-radius: 8px; padding: 6px 12px; font-size: 12px; cursor: pointer; margin-bottom: 16px; }
.pnl-back:hover { border-color: var(--accent); color: var(--accent); }

/* buckets */
.bk-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(200px, 1fr)); gap: 13px; }
.bk-card {
  text-align: left; background: var(--bg-1); border: 1px solid var(--line); border-radius: 15px;
  padding: 17px 18px; cursor: pointer; transition: border-color 0.15s, transform 0.12s, box-shadow 0.2s;
  animation: settle 0.4s ease both;
}
.bk-card:hover { border-color: hsl(var(--h) 45% 55% / 0.6); transform: translateY(-2px); box-shadow: 0 8px 26px hsl(var(--h) 50% 50% / 0.10); }
.bk-top { display: flex; align-items: center; gap: 8px; margin-bottom: 12px; }
.bk-dot { width: 9px; height: 9px; border-radius: 50%; background: hsl(var(--h) 55% 60%); box-shadow: 0 0 9px hsl(var(--h) 55% 60% / 0.7); display: inline-block; }
.bk-name { font-size: 14px; font-weight: 650; }
.bk-n { font-size: 27px; font-weight: 750; font-variant-numeric: tabular-nums; line-height: 1; }
.bk-n.dim { color: var(--ink-3); }
.bk-l { font-size: 9.5px; color: var(--ink-3); text-transform: uppercase; letter-spacing: 0.06em; margin-top: 4px; }
.bk-crew { display: flex; gap: 4px; margin-top: 13px; flex-wrap: wrap; }
.bk-face {
  width: 24px; height: 24px; display: grid; place-items: center; font-size: 12px;
  border-radius: 7px; background: var(--bg-2); border: 1px solid var(--line);
}
.bk-more { font-size: 10px; color: var(--ink-3); align-self: center; }
.bk-agents { margin-top: 8px; font-size: 10.5px; color: var(--ink-3); line-height: 1.5; }

.mem-list { display: flex; flex-direction: column; gap: 6px; }
.mem-row {
  display: flex; align-items: baseline; gap: 13px; background: var(--bg-1);
  border: 1px solid var(--line); border-radius: 10px; padding: 10px 14px; animation: settle 0.35s ease both;
}
.mem-when { font-size: 10.5px; color: var(--accent-2); white-space: nowrap; min-width: 68px; font-variant-numeric: tabular-nums; }
.mem-label { font-size: 13px; }

/* reports timeline */
.rep-filter { display: flex; gap: 7px; flex-wrap: wrap; margin-bottom: 20px; }
.chip.tap { cursor: pointer; transition: transform 0.1s, background 0.15s; }
.chip.tap:hover { transform: translateY(-1px); }
.timeline { position: relative; padding-left: 22px; }
.timeline::before { content: ""; position: absolute; left: 5px; top: 6px; bottom: 6px; width: 1px; background: var(--line); }
.tl-row { position: relative; margin-bottom: 15px; animation: settle 0.35s ease both; }
.tl-dot {
  position: absolute; left: -21px; top: 12px; width: 9px; height: 9px; border-radius: 50%;
  background: hsl(var(--h) 55% 60%); box-shadow: 0 0 9px hsl(var(--h) 55% 60% / 0.7);
}
.tl-body { background: var(--bg-1); border: 1px solid var(--line); border-radius: 12px; padding: 11px 15px; transition: border-color 0.15s, transform 0.12s; }
.tl-row:hover .tl-body { border-color: hsl(var(--h) 45% 50% / 0.5); transform: translateX(2px); }
.tl-top { display: flex; align-items: center; gap: 8px; }
.tl-ava {
  width: 24px; height: 24px; flex: 0 0 24px; display: grid; place-items: center; font-size: 12px;
  border-radius: 7px; background: hsl(var(--h) 42% 22% / 0.8); border: 1px solid hsl(var(--h) 45% 45% / 0.3);
}
.tl-agent { font-size: 12.5px; font-weight: 650; }
.tl-when { font-size: 10.5px; color: var(--ink-3); margin-left: auto; white-space: nowrap; font-variant-numeric: tabular-nums; }
.tl-label { font-size: 12px; color: var(--ink-3); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.tl-sum { margin: 7px 0 0 32px; font-size: 12.5px; line-height: 1.6; color: var(--ink-2); }

/* rules */
.rule-list { display: flex; flex-direction: column; gap: 9px; }
.rule-card { background: var(--bg-1); border: 1px solid var(--line); border-radius: 11px; padding: 12px 15px 10px; animation: settle 0.35s ease both; transition: border-color 0.15s; }
.rule-card:hover { border-color: var(--accent); }
.rule-top { display: flex; align-items: baseline; gap: 10px; margin-bottom: 5px; }
.rule-ref { font-family: var(--mono); font-size: 12.5px; }
.rule-scope { font-size: 9.5px; text-transform: uppercase; letter-spacing: 0.07em; color: var(--accent); background: var(--accent-dim); border-radius: 5px; padding: 2px 7px; }
.rule-meta { font-size: 11.5px; color: var(--ink-3); line-height: 1.6; }
.rule-meta b { color: var(--ink-2); font-weight: 600; }
.rule-bar { margin-top: 9px; height: 3px; border-radius: 99px; background: var(--bg-2); overflow: hidden; }
.rule-bar i { display: block; height: 100%; border-radius: 99px; background: linear-gradient(90deg, var(--accent), var(--accent-2)); transition: width 0.6s ease; }

/* graph */
.graph-wrap { flex: 1; min-height: 0; display: flex; }
.graph-frame { flex: 1; border: none; background: #06080e; }

/* dossier extras */
.doss-head-actions { margin-left: auto; display: flex; gap: 6px; }
.doss-3d { background: var(--accent-dim); border: 1px solid rgba(79, 184, 160, 0.35); color: var(--accent); border-radius: 8px; padding: 6px 10px; font-size: 11px; cursor: pointer; white-space: nowrap; }
.doss-3d:hover { border-color: var(--accent); }

/* dossier edit mode — every field of the agent, saved into the draft */
.doss-edit { display: flex; flex-direction: column; gap: 10px; background: var(--bg-1); border: 1px solid rgba(79, 184, 160, 0.3); border-radius: 12px; padding: 13px 14px; margin-bottom: 20px; animation: settle 0.25s ease both; }
.doss-edit label { display: flex; flex-direction: column; gap: 4px; font-size: 10px; text-transform: uppercase; letter-spacing: 0.07em; color: var(--ink-3); }
.doss-edit label em { font-style: normal; text-transform: none; letter-spacing: 0; color: var(--ink-3); font-size: 9.5px; }
.doss-edit input, .doss-edit textarea { background: var(--bg-2); border: 1px solid var(--line); color: var(--ink); border-radius: 8px; padding: 8px 10px; font-size: 12.5px; font-family: var(--font); resize: vertical; }
.doss-edit input:focus, .doss-edit textarea:focus { outline: none; border-color: var(--accent); }
.doss-edit-row2 { display: grid; grid-template-columns: 1fr 72px; gap: 8px; }
.doss-edit-actions { display: flex; gap: 8px; margin-top: 2px; }

/* machine trays — the automations an agent operates, chips with health lights */
/* the machine rack — a recessed slot flush under the owner's card */
.oc-tray {
  display: flex; flex-wrap: wrap; gap: 4px; justify-content: center;
  max-width: 210px; margin-top: -4px; padding: 10px 8px 7px;
  background: transparent; border: 0; padding: 8px 0 0;
}
.oc-tray.fail { border-color: rgba(224, 123, 106, 0.5); box-shadow: inset 0 3px 8px rgba(0, 0, 0, 0.5), 0 6px 18px -8px rgba(224, 123, 106, 0.28); }
.oc-tray.warn { border-color: rgba(217, 160, 91, 0.42); }
.oc-mac {
  display: inline-flex; align-items: center; gap: 6px;
  background: var(--bg-2); border: 1px solid var(--line);
  border-radius: 8px; padding: 5px 9px; cursor: pointer;
  font-family: var(--mono); font-size: 9.5px; color: var(--ink-2);
  transition: border-color .18s var(--ease), transform .12s var(--ease), box-shadow .2s var(--ease);
}
.oc-mac:hover { border-color: var(--accent); color: var(--ink); transform: translateY(-1px); }
.oc-mac.sel { border-color: var(--accent); background: var(--accent-dim); color: var(--ink); }
.oc-mac.more { color: var(--ink-3); font-style: italic; }
.oc-mac.dragging { opacity: 0.45; cursor: grabbing; }
.oc-mac.more:hover { color: var(--accent); }
.mac-emoji { font-size: 11px; }
/* real vendor marks, tinted to the house so twelve logos read as one system.
   Full brand colour on hover — recognition when you want it, calm when you
   don't. */
/* the hero's treatment: a real vendor mark on a WHITE chip. Twelve tinted
   monochrome logos read as a sticker album; twelve white chips read as a rack
   of real systems — and it is the one thing on the old board that already
   looked genuine, so everything else was raised to it rather than it lowered. */
.mac-brand {
  width: 24px; height: 24px; flex: 0 0 24px; display: block;
  background: var(--bg-2); border: 1px solid var(--line); border-radius: 7px;
  padding: 4px; box-sizing: border-box;
  transition: transform .2s ease, box-shadow .2s ease;
}
.oc-mac:hover .mac-brand,
.oc-mac.sel .mac-brand { transform: scale(1.06); box-shadow: 0 5px 14px -5px rgba(0, 0, 0, 0.85); }
.mac-name { white-space: nowrap; max-width: 76px; overflow: hidden; text-overflow: ellipsis; }
.mac-dot { width: 7px; height: 7px; border-radius: 50%; flex: 0 0 7px; display: inline-block; }
.mac-dot.ok { background: var(--accent); box-shadow: 0 0 6px rgba(79, 184, 160, 0.7); }
.mac-dot.warn { background: var(--warn); box-shadow: 0 0 6px rgba(224, 180, 95, 0.7); }
.mac-dot.fail { background: #e07b6a; box-shadow: 0 0 7px rgba(224, 123, 106, 0.8); animation: pulse 1.4s ease-in-out infinite; }
.mac-dot.none { background: var(--ink-3); }
/* green, but it failed earlier in the window — a faint amber ring, never a tint */
.mac-dot.ok.unstable { box-shadow: 0 0 6px rgba(79, 184, 160, 0.7), 0 0 0 2px rgba(224, 180, 95, 0.3); }

/* automation dossier health header */
.doss-health {
  display: flex; align-items: center; gap: 10px; flex-wrap: wrap;
  background: var(--bg-1); border: 1px solid var(--line); border-radius: 10px;
  padding: 10px 13px; margin-bottom: 16px; font-size: 11.5px; color: var(--ink-2);
}
.doss-health b { color: var(--ink); font-size: 12px; }
.doss-health.fail { border-color: rgba(224, 123, 106, 0.5); }
.doss-health.warn { border-color: rgba(224, 180, 95, 0.4); }
.doss-health.ok { border-color: rgba(79, 184, 160, 0.35); }
.doss-auto-when { margin-left: auto; font-size: 10px; color: var(--ink-3); white-space: nowrap; }

/* automations — machines an agent operates, listed in its dossier */
.auto-badge { font-size: 9px; text-transform: uppercase; letter-spacing: 0.08em; color: var(--warn); background: rgba(224, 180, 95, 0.1); border: 1px solid rgba(224, 180, 95, 0.3); border-radius: 5px; padding: 2px 7px; vertical-align: middle; margin-left: 6px; }
.doss-autos { display: flex; flex-direction: column; gap: 5px; }
.doss-auto { display: flex; align-items: baseline; gap: 9px; text-align: left; background: var(--bg-1); border: 1px solid var(--line); border-radius: 9px; padding: 8px 11px; cursor: pointer; transition: border-color 0.15s; }
.doss-auto:hover { border-color: var(--warn); }
.doss-auto-emoji { font-size: 13px; }
.doss-auto-name { font-size: 12px; font-weight: 600; white-space: nowrap; }
.doss-auto-role { font-size: 10.5px; color: var(--ink-3); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }

.doss-foot { display: flex; flex-direction: column; gap: 8px; margin-top: 6px; padding-top: 14px; border-top: 1px solid var(--line); }
.btn.danger { border-color: rgba(224, 123, 106, 0.45); color: #e07b6a; background: transparent; }
.btn.danger:hover { background: rgba(224, 123, 106, 0.1); }
.bk-agents.unassigned { color: var(--ink-3); font-style: italic; }

.pending {
  position: relative; z-index: 2; display: flex; gap: 8px; flex-wrap: wrap; align-items: center;
  padding: 10px 26px; border-bottom: 1px solid var(--line); background: var(--warn-wash);
}
.pending-lead {
  font-family: var(--mono); font-size: 9px; letter-spacing: .18em; text-transform: uppercase;
  color: var(--warn); margin-right: 2px;
}
/* every pending change is its own undo button. A global discard makes one
   mis-drop cost every other edit, so people stop dragging entirely. */
.pending-item {
  display: inline-flex; align-items: center; gap: 8px; cursor: pointer;
  font-size: 11.5px; font-family: var(--mono); color: var(--ink-2);
  background: var(--bg-1); border: 1px solid var(--line); border-radius: 100px;
  padding: 4px 6px 4px 12px;
  transition: border-color .18s var(--ease), color .18s ease, transform .16s var(--ease);
}
.pending-item i {
  font-style: normal; font-size: 8.5px; letter-spacing: .12em; text-transform: uppercase;
  color: var(--warn); border: 1px solid rgba(184,134,44,.3); border-radius: 100px; padding: 2px 7px;
  transition: background .18s ease, color .18s ease;
}
.pending-item:hover { border-color: var(--warn); color: var(--ink); transform: translateY(-1px); }
.pending-item:hover i { background: var(--warn); color: var(--bg-1); }

/* the lane lights up as a drop target, so a near-miss is impossible */
.oc-row.lanes > .oc-child.lane-over {
  border-color: var(--accent); background: var(--accent-dim);
  box-shadow: 0 0 0 3px var(--accent-dim), var(--sh-2);
}
.pnl-err { position: relative; z-index: 2; padding: 10px 26px; color: #e07b6a; font-size: 12.5px; }

/* layout — 100% so a HOST container decides the height (embedded panel);
   the standalone app gives html/body/#root 100%, so served behaviour is unchanged. */
.pnl { height: 100%; min-height: 480px; }
.body { position: relative; z-index: 1; flex: 1; display: flex; min-height: 0; }
.tree { position: relative; flex: 1; min-width: 0; padding: 24px 26px 24px; overflow: hidden;
  display: flex; flex-direction: column;
  /* the ground plane: a faint dot grid (engineered surface, drag affordance)
     + a verdigris pool anchoring the eye at the root. Static — capture-safe. */
  background:
    radial-gradient(900px 420px at 50% 120px, rgba(79, 184, 160, 0.05), transparent 70%),
    radial-gradient(circle at 1px 1px, var(--dot) 1px, transparent 1.5px);
  background-size: auto, 28px 28px;
}
.tree-hint { color: var(--ink-3); font-family: var(--mono); font-size: 10px; letter-spacing: .05em; margin: 0 0 14px; text-align: center; }

/* ── RANK HEADERS (from the ministry organigram) ───────────────────────────
   Rank is NAMED, never inferred from indentation. Roman numerals + a rule
   under each, spanning the columns the cascade actually occupies. */
/* four headers over the four real cascade columns: law · gm · departments ·
   staff. Widths mirror .cascade so a header sits over the column it names —
   headers labelling columns that do not exist is worse than no headers. */
.ranks {
  display: grid;
  grid-template-columns: 232px var(--rail-w, 56px) 268px var(--rail-w, 56px) minmax(232px, 300px) var(--rail-w, 56px) 1fr;
  margin: 0 0 16px; padding: 0 16px; flex: 0 0 auto;
}
.rank:nth-child(1) { grid-column: 1; }
.rank:nth-child(2) { grid-column: 3; }
.rank:nth-child(3) { grid-column: 5; }
.rank:nth-child(4) { grid-column: 7; }
.rank {
  font-family: var(--mono); font-size: 9px; letter-spacing: .2em; text-transform: uppercase;
  color: var(--ink-3); padding-bottom: 8px; border-bottom: 1px solid rgba(217, 160, 91, 0.16);
  position: relative; white-space: nowrap; overflow: hidden; text-overflow: ellipsis;
}
.rank b { color: var(--brass); font-weight: 500; margin-right: 7px; }
.rank::after { content: ""; position: absolute; left: 0; bottom: -1px; width: 24px; height: 1px; background: var(--brass); }

/* the constellation — the hero's own atmosphere, drawn once behind the rack.
   Gradient + points only; NO grain/noise overlay (it read as a blurry filter
   smeared across the board). */
.pnl-stars { position: fixed; inset: 0; z-index: 0; pointer-events: none; opacity: 0; width: 100%; height: 100%; }

/* THE COMPANY CHART — root on top, branches fanning beneath. Connectors are
   crafted: curved elbows at the row's ends, branch-hued drops, a glowing
   junction node where the parent's line meets the bar. Pure CSS. */
/* the measuring viewport — flex:1 + min-height:0 lets it consume the height
   .tree gives it; align/justify center the scaled block for narrow orgs. */
/* Always scrollable. It used to be overflow:hidden unless the user manually
   zoomed — safe only while auto-fit guaranteed the whole board fit one screen.
   A lane board grows downward, so that assumption sealed every lane below the
   fold behind an invisible wall. */
.chart-fit { position: relative; flex: 1; min-height: 0; display: flex; align-items: flex-start; justify-content: center; overflow: auto; }
/* transform:scale() does not change layout size, so the scaled block gets a
   spacer sized to its VISUAL footprint — otherwise the scroll extent is the
   unscaled height and you scroll into empty space. */
/* overflow:hidden clips the UNSCALED layout box of the absolutely-positioned
   chart, which otherwise adds its full natural height to the scroll extent —
   ~900px of empty scroll past the last lane. The visual (scaled) content is
   exactly the spacer's size, so nothing real is clipped. */
.chart-scaled { position: relative; flex: 0 0 auto; overflow: hidden; }
.chart-scaled > .chart { position: absolute; top: 0; left: 50%; transform-origin: top center; }
.chart-fit.zoomed .chart-scaled > .chart { left: 0; transform-origin: top left; }
/* user-zoomed: native scroll is the pan; top-left origin keeps the scaled
   overflow fully reachable (top/center origin would clip the left half). */
.chart-fit.zoomed { overflow: auto; justify-content: flex-start; }
.chart-fit.zoomed .chart { transform-origin: top left; }
.zoomer {
  position: absolute; right: 34px; bottom: 32px; z-index: 3; display: flex; align-items: center; gap: 2px;
  font-family: var(--mono); font-size: 11px; color: var(--ink-2);
  background: var(--bg-2); border: 1px solid var(--line); border-radius: 8px; padding: 3px 6px;
  box-shadow: 0 4px 18px rgba(0, 0, 0, 0.35);
}
.zoomer button {
  all: unset; cursor: pointer; padding: 2px 8px; border-radius: 5px; color: var(--ink-2);
  font-family: var(--mono); font-size: 12px; line-height: 1.4;
}
.zoomer button:hover { background: var(--accent-dim); color: var(--ink); }
.zoomer button.on { color: var(--accent); }
.zoomer-pct { min-width: 40px; text-align: center; color: var(--ink-3); }
.zoomer-sep { width: 1px; height: 16px; background: var(--line); margin: 0 2px; }

/* ── the ledger shelf: every bucket as a pigeonhole, hover a role to see its
   reach. Docked under the chart, always visible — the memory half of the
   two pillars (structure above, memory below), never a separate tab. */
.ledger-shelf {
  position: relative; z-index: 2; flex: 0 0 auto; margin-top: 14px;
  padding: 10px 16px 12px; border-radius: 10px;
  border: 1px solid var(--line); background: var(--bg-1); box-shadow: var(--sh-2);
  width: min(1180px, 92vw);
}
.shelf-label {
  display: block; font-family: var(--mono); font-size: 9px; letter-spacing: 0.14em;
  text-transform: uppercase; color: var(--brass); margin-bottom: 8px;
}
.shelf-slots { display: flex; flex-wrap: wrap; gap: 6px; }
.shelf-slot {
  font-family: var(--mono); font-size: 10px; color: var(--ink-3);
  background: var(--bg-2); border: 1px solid var(--line); border-radius: 5px;
  padding: 4px 9px; transition: border-color .18s ease, color .18s ease, box-shadow .25s ease, transform .18s ease;
}
.shelf-slot.lit {
  color: var(--brass-hi); border-color: var(--brass); transform: translateY(-1px);
  box-shadow: 0 0 0 1px rgba(201, 160, 74, 0.3), 0 6px 16px -6px rgba(201, 160, 74, 0.5);
  background: rgba(201, 160, 74, 0.1);
}
.shelf-slot.sealed { color: var(--ink-3); font-style: italic; border-style: dashed; opacity: 0.75; }
.shelf-slot.sealed.lit { color: var(--ink-3); border-color: var(--line); background: var(--bg-2); box-shadow: none; transform: none; }
@media (prefers-reduced-motion: reduce) { .shelf-slot { transition: none; } }

/* the law toggle in the top bar */
.law-toggle { font-family: var(--mono); letter-spacing: 0.02em; }
.law-toggle.on { color: var(--brass-hi); border-color: var(--brass); background: rgba(201, 160, 74, 0.12); }
/* min-width:max-content keeps connectors geometrically correct at natural size
   BEFORE scaling; the measured --fit shrinks the whole block toward its head. */
/* transform is set inline by Panel.tsx (see the note there) — only origin,
   sizing and the easing live here. */
.chart {
  min-width: max-content; padding: 8px 14px 20px;
  transform-origin: top center; position: relative; /* the rail plane's origin */
  transition: transform 0.35s cubic-bezier(0.22, 1, 0.36, 1); will-change: transform;
}
/* plates sit above the rail plane */
.chart .cascade { position: relative; z-index: 1; }

/* rank I — the law. Brass-edged like the GM but unfilled: it is a document,
   not an operator. */
.law-plate { width: 232px; cursor: pointer; }
.law-plate .ag-ava { font-family: var(--display); color: var(--accent); }
.law-plate .ag-name { color: var(--accent); font-size: 13px; }
.law-plate .ag-role { word-break: break-all; }
/* ── THE CASCADE (master-key structure) ───────────────────────────────────
   Rank runs LEFT TO RIGHT, one column each, exactly as a master-key chart
   reads: THE STANDARD → GM → departments → staff. Two nested grids give the
   four columns; the brass elbows between them are drawn by CascadeRails as
   one measured SVG (orthogonal geometry between arbitrary boxes is not a
   thing CSS pseudo-elements can do honestly). */
.cascade {
  display: grid;
  grid-template-columns: max-content var(--rail-w, 56px) 1fr;
  /* START, not centre. Centring is right for a 3-branch key chart; with nine
     departments the stack is ~2,200px tall, so it buried the master key and the
     GM below the fold — the two plates that must be seen first. Top-aligned
     also matches the ministry chart's reading order. */
  align-items: start;
}
.cascade > .law-plate { grid-column: 1; }
.cascade > .ocn { grid-column: 3; }

/* rank II–IV live inside the root .ocn, which is itself a cascade */
.cascade > .ocn {
  display: grid;
  /* the lanes column is BOUNDED so staff wrap inside their lane. Left at 1fr
     under .chart's max-content sizing it grew to fit every staff plate on one
     row — 2,400px natural width, which fit-to-width then scaled to 52% and made
     every plate unreadable. Rank IV wraps; the board stays legible. */
  grid-template-columns: max-content var(--rail-w, 56px) minmax(420px, 940px);
  grid-template-areas: "gm rail lanes";
  align-items: start;
}
.cascade > .ocn > .casc-head { grid-area: gm; display: flex; flex-direction: column; align-items: stretch; }
.cascade > .ocn > .oc-down { grid-area: rail; }
.cascade > .ocn > .oc-row.lanes { grid-area: lanes; }

/* the SVG rail plane — sits under the plates, never intercepts a click */
.rails { position: absolute; inset: 0; z-index: 0; pointer-events: none; overflow: visible; width: 100%; height: 100%; }

.ocn { display: flex; flex-direction: column; align-items: center; }
/* the connective tissue reads brass everywhere — a company chart drawn with
   the house's own material, not a generic diagram line. */
.oc-down { width: 2px; height: 18px; position: relative; background: var(--brass-line); opacity: 0.75; }
.oc-down::after { content: ""; position: absolute; bottom: -2px; left: 50%;
  width: 5px; height: 5px; transform: translateX(-50%); border-radius: 50%;
  background: var(--brass-hi); box-shadow: 0 0 8px rgba(201, 160, 74, 0.55); }
.oc-row { display: flex; align-items: flex-start; }

/* ── THE STAFF BOARD: departments as lanes, stacking DOWNWARD ──────────────
   Nine departments fanned sideways forced a canvas nobody could read at 17%
   zoom. Each lane is a row of the board: a brass rail down the left, the
   head's card, then its people flowing right and wrapping inside the lane.
   The board scrolls like a document; every card stays at legible size. */
/* the lanes are rank III+IV: one shelf per department, stacked. Width now comes
   from the cascade's 1fr column, not a hardcoded viewport clamp. */
.oc-row.lanes {
  flex-direction: column;
  align-items: stretch;
  gap: 14px;
  padding-top: 0;
  width: 100%;
}
/* a lane is a SHELF on the rack — a hairline tray, not a coloured panel. The
   old lane had a hash-hue left border and tint per department; the rack is one
   material throughout and the department is named, not coloured. */
.oc-row.lanes > .oc-child {
  flex: 1 1 auto;
  position: relative;
  border: 1px solid var(--line);
  border-radius: 18px;
  background: var(--surface-tray);
  padding: 16px 18px 18px;
  transition: border-color .25s ease, box-shadow .35s var(--ease);
}
.oc-row.lanes > .oc-child:hover { border-color: var(--line-2, #d9d3c9); box-shadow: var(--sh-2); }
@media (prefers-reduced-motion: reduce) {
  .oc-row.lanes > .oc-child:hover { transform: none; }
}
/* lanes own their connectors — kill the fan's drop-lines inside them */
.oc-row.lanes > .oc-child::before,
.oc-row.lanes > .oc-child::after { display: none; }
.oc-row.lanes > .oc-child > .ocn > .oc-down { display: none; }

/* inside a lane: head card top-left, its service tray beneath the head, a
   brass rail column, its people filling the right. Explicit areas — an
   implicit 2-column grid put the tray in the staff slot the moment every
   department gained services, which shunted the people into a one-card
   column. The rail column is the elbow HANDOFF.md flagged as hidden: the
   department head commanding its people, drawn once, orthogonally. */
.oc-row.lanes > .oc-child > .ocn {
  display: grid;
  grid-template-columns: minmax(278px, 300px) var(--rail-w, 56px) 1fr;
  grid-template-areas:
    "head rail staff"
    "macs rail staff";
  grid-template-rows: auto 1fr;
  align-items: start;
  gap: 10px 0;
}
.oc-row.lanes > .oc-child > .ocn > .ag      { grid-area: head; }
.oc-row.lanes > .oc-child > .ocn > .oc-tray { grid-area: macs; }
.oc-row.lanes > .oc-child > .ocn > .oc-row  { grid-area: staff; margin-left: 4px; }

/* the rail: a vertical brass spine for the department, capped where it meets
   the head, with one orthogonal branch reaching into the staff block. This
   is the ".oc-down" element — hidden below (line ~490 in the old cascade),
   here it's re-purposed as the rail instead of the plain tree drop-line. */
.oc-row.lanes > .oc-child > .ocn > .oc-down {
  display: block; grid-area: rail; position: relative; width: 100%; height: 100%;
  min-height: 44px;
  /* the base .oc-down is a 2px-wide FILLED brass drop-line. Widening it to the
     rail column without clearing its background painted a solid brass slab down
     every lane — the rail is drawn by ::before/::after, not by the box itself. */
  background: none;
}
/* No ::before/::after brass here any more — the SVG rail plane draws every
   connector from measured box positions. Leaving these would double each rail. */

/* semantic zoom lever: the rail itself is the fold/unfold control at the
   department level — house → department → role, one click at a time. */
.oc-down.foldable { cursor: pointer; }
.oc-down.foldable:focus-visible { outline: 2px solid var(--brass); outline-offset: 2px; border-radius: 4px; }
.oc-fold-glyph {
  position: absolute; left: 50%; top: 22px; transform: translate(-50%, -50%);
  font-style: normal; font-size: 10px; line-height: 1; width: 15px; height: 15px;
  display: grid; place-items: center; border-radius: 50%;
  background: var(--bg-1); border: 1px solid var(--line-2); color: var(--accent);
  transition: transform .15s ease, background .15s ease;
}
.oc-down.foldable:hover .oc-fold-glyph { background: rgba(201, 160, 74, 0.18); transform: translate(-50%, -50%) scale(1.15); }
.oc-down.folded .oc-fold-glyph { color: var(--ink-2); border-color: var(--line); }

/* the folded department: head visible, staff summarised to one line — the
   "department" rung of house → department → role. */
.oc-folded-summary {
  grid-area: staff; align-self: center; justify-self: start; text-align: left;
  background: none; border: 1px dashed var(--line); border-radius: 8px;
  padding: 9px 13px; margin-left: 4px; cursor: pointer;
  font-family: var(--mono); font-size: 11px; color: var(--ink-3);
  transition: border-color .15s ease, color .15s ease;
}
.oc-folded-summary:hover { border-color: var(--brass); color: var(--brass-hi); }
/* "show the law": the SAME rails, re-read as authority. The SVG plane swaps to
   a travelling dashed brass so the law is seen flowing down the cascade. */
.rail-line { stroke: var(--line-2, #d9d3c9); stroke-width: 1.5; stroke-linecap: round; fill: none; }
.rail-dash { stroke: var(--accent-2); stroke-width: 1; fill: none; stroke-dasharray: 2 9; opacity: 0; }
.law-on .rail-line { stroke: var(--brass-hi); stroke-width: 1.9; opacity: .9; }
.law-on .rail-dash { opacity: .95; animation: rail-flow 700ms linear infinite; }
@keyframes rail-flow { to { stroke-dashoffset: -11; } }
@media (prefers-reduced-motion: reduce) { .law-on .rail-dash { animation: none; } }

/* the tray is the department's stack of real services — one per line, so the
   vendor marks read as a list of systems rather than a scatter of chips */
.oc-row.lanes > .oc-child > .ocn > .oc-tray {
  display: flex; flex-direction: column; align-items: stretch;
  gap: 4px; margin: 0; padding: 0; max-width: 232px;
}
.oc-row.lanes > .oc-child > .ocn > .oc-tray > .oc-mac { justify-content: flex-start; width: 100%; }
.oc-row.lanes > .oc-child > .ocn > .oc-tray > .oc-mac .mac-name { max-width: none; }

@media (max-width: 820px) {
  .oc-row.lanes > .oc-child > .ocn {
    grid-template-columns: 1fr;
    grid-template-areas: "head" "macs" "staff";
  }
  /* no rail column on a single-column stack — the rail has nothing to span */
  .oc-row.lanes > .oc-child > .ocn > .oc-down { display: none; }
  .oc-row.lanes > .oc-child > .ocn > .oc-tray { max-width: none; flex-direction: row; flex-wrap: wrap; }
}
/* inside a lane the people always flow right and wrap — the ".wrap" grid
   (which grows downward) would otherwise stack a big department into a
   one-card-wide column. Specificity here deliberately beats .oc-row.wrap. */
.oc-row.lanes > .oc-child > .ocn > .oc-row,
.oc-row.lanes > .oc-child > .ocn > .oc-row.wrap {
  display: flex;
  flex-direction: row;
  flex-wrap: wrap;
  justify-content: flex-start;
  gap: 8px;
  margin: 0;
  padding: 0;
  max-width: none;
  border: 0;
  border-radius: 0;
  background: none;
  align-content: flex-start;
}
.oc-row.lanes > .oc-child > .ocn > .oc-row > .oc-child { padding: 0; flex: 0 0 auto; }
.oc-row.lanes > .oc-child > .ocn > .oc-row > .oc-child::before,
.oc-row.lanes > .oc-child > .ocn > .oc-row > .oc-child::after { display: none; }

@media (max-width: 820px) {
  .oc-row.lanes > .oc-child > .ocn { grid-template-columns: 1fr; gap: 12px; }
}
/* Connectors are drawn by the SVG rail plane now, not by pseudo-elements. The
   old fan drop-lines/elbows here would double every rail. */
.oc-child { position: relative; padding: 0; display: flex; flex-direction: column; align-items: center; }
.oc-child::before, .oc-child::after { display: none; }

/* wide sibling sets — grouped subtrees that wrap to natural width (never crush a
   branch into a fixed cell — that overflowed and collided with the next branch) */
.oc-row.wrap {
  display: flex; flex-wrap: wrap; justify-content: center; align-items: flex-start;
  gap: 10px 18px; margin: 0 auto; padding: 12px 14px 14px;
  max-width: min(100%, 840px);
  border: 1px solid var(--line); border-radius: 18px; background: rgba(16, 19, 26, 0.35);
}
.oc-row.wrap > .oc-child { padding: 8px 4px 0; flex: 0 0 auto; }
.oc-row.wrap > .oc-child::before, .oc-row.wrap > .oc-child::after { display: none; }

/* ── THE PLATE ────────────────────────────────────────────────────────────
   An engraved plate on a key rack. Left edge is milled brass; rank reads
   through FINISH and SIZE (polished → satin → dulled), never hue. Radius 4px
   per CRAFT §0 (radii 2/3/6) — the old 15px rounded rect is what made this
   read as a SaaS card. Content is left-aligned like a name plate, not
   centred like a business card. */
/* ══ THE SOURCE CARD (variant B — "the spine") ══════════════════════════
   This board is not a picture of the org: it IS the org file booboo_boot
   reads. Rules inherit down it, bucket reach derives from it, every agent
   boots against it. So the card states its CONSEQUENCE, not just its
   attributes — what it declares, who it binds, what it boots on.
   Health is the card's own left edge, so scanning nine stacked departments
   you find the amber one peripherally, before reading a single word. */
.ag {
  position: relative; display: flex; flex-direction: column; align-items: stretch;
  width: calc(300px - min(var(--d, 0), 2) * 22px); /* 300 / 278 / 256 by rank */
  padding: 15px 18px 13px 21px; text-align: left;
  background: var(--bg-1);
  border: 1px solid var(--line); border-radius: 14px; cursor: grab; overflow: hidden;
  box-shadow: var(--sh-2);
  transition: box-shadow .22s var(--ease), transform .22s var(--ease), border-color .18s ease, opacity .18s ease;
  animation: settle .45s var(--settle) both;
}
/* the spine — health as the card's own edge */
.ag::before {
  content: ""; position: absolute; left: 0; top: 0; bottom: 0; width: 4px;
  background: var(--ink-3); transition: background .2s ease;
}
.ag.h-ok::before { background: var(--ok); }
.ag.h-warn::before { background: var(--warn); }
.ag.h-fail::before { background: var(--fail); }
/* an unhealthy card also carries a wash, so the state survives a greyscale
   print and never rests on hue alone */
.ag.h-warn { background: linear-gradient(180deg, var(--warn-wash), var(--bg-1) 52%); border-color: #ecd9ae; }
.ag.h-fail { background: linear-gradient(180deg, var(--fail-wash), var(--bg-1) 52%); border-color: #edc9bf; }
@keyframes settle { from { opacity: 0; transform: translateY(8px) scale(.985); } to { opacity: 1; transform: none; } }
.ag:hover { transform: translateY(-2px); box-shadow: var(--sh-3); border-color: var(--line-2); }
.ag:active { transform: translateY(0) scale(.995); transition-duration: .08s; }
.ag.sel { border-color: var(--accent); box-shadow: var(--sh-3), 0 0 0 3px var(--accent-dim); }
.ag:focus-visible { outline: 2px solid var(--accent); outline-offset: 2px; }
.ag.over { border-color: var(--accent-2); box-shadow: var(--sh-3), 0 0 0 4px var(--accent-dim); transform: scale(1.02); }
.ag.dragging { opacity: 0.4; cursor: grabbing; }

/* WHERE IT BELONGS — reads first, so a card lifted out of its lane still
   knows its own place. */
.ag-eyebrow {
  font-family: var(--mono); font-size: 9px; letter-spacing: .16em; text-transform: uppercase;
  color: var(--accent); display: block; margin-bottom: 7px;
}
/* WHAT FLOWS OUT — the consequence line. Plain English, never glyphs. */
.ag-flows {
  display: block; font-size: 11.5px; color: var(--ink-3); margin-top: 10px;
  font-variant-numeric: tabular-nums;
}

/* ── THE HEALTH LIGHT ──────────────────────────────────────────────────────
   A real lamp: a lit core inside a soft halo, with a slow breath so a healthy
   board is visibly ALIVE rather than merely static. The halo is a separate
   ::after ring that expands and fades — one pulse every 2.6s, offset per
   bubble so nine departments never blink in unison (a synchronised board
   reads as a screensaver; a staggered one reads as a building). */
.ag-light {
  position: absolute; top: 13px; right: 14px; width: 8px; height: 8px; border-radius: 50%;
  background: var(--ink-3);
}
.ag-light::after {
  content: ""; position: absolute; inset: -3px; border-radius: 50%;
  border: 1px solid currentColor; opacity: 0;
  animation: lamp 2.6s var(--ease) infinite;
  animation-delay: var(--lamp-delay, 0s);
}
.ag-light.ok { background: var(--ok); color: var(--ok); box-shadow: 0 0 0 3px var(--ok-wash); }
.ag-light.warn { background: var(--warn); color: var(--warn); box-shadow: 0 0 0 3px var(--warn-wash); }
.ag-light.fail { background: var(--fail); color: var(--fail); box-shadow: 0 0 0 3px var(--fail-wash); }
/* a failing lamp beats faster — urgency in the rhythm, not just the hue */
.ag-light.fail::after { animation-duration: 1.2s; }
@keyframes lamp {
  0% { transform: scale(.7); opacity: .85; }
  70%, 100% { transform: scale(1.9); opacity: 0; }
}
@media (prefers-reduced-motion: reduce) { .ag-light::after { animation: none; } }

/* rank I·II — the GM. Polished brass: the only plate that is lit rather than lit-upon. */
.ag.root { cursor: default; width: 268px; padding: 15px 17px;
  background: var(--surface-lift);
  border-color: var(--surface-lift-edge); box-shadow: var(--sh-3); }
.ag.root .ag-name { font-size: 14.5px; }

/* plate header: the mark sits BESIDE the name, not above it — a name plate,
   not a business card. Staff plates carry no mark at all (see Panel.tsx): a
   brass plaque does not have a cartoon on it, and 51 identical 🤖 was the
   cheapest token on the board. */
.ag-head { display: flex; align-items: center; gap: 9px; min-width: 0; }
.ag-ava {
  width: 26px; height: 26px; flex: 0 0 26px; display: grid; place-items: center; font-size: 14px;
  border-radius: 9px; background: var(--accent-dim); border: 1px solid #eadcc3;
}
.ag.root .ag-ava { width: 30px; height: 30px; flex-basis: 30px; font-size: 16px; border-color: rgba(239, 195, 137, 0.45); }

/* the name — engraved: a dark groove under, a hairline of light above */
.ag-name {
  font-family: var(--display); font-size: 18px; font-weight: 600; letter-spacing: -0.015em;
  line-height: 1.18; color: var(--ink);
  white-space: nowrap; max-width: 100%; overflow: hidden; text-overflow: ellipsis;
}
/* staff plates: quieter, lighter weight — rank in the type as well as the metal */
.ag.staff .ag-name { font-family: var(--font); font-size: 15px; font-weight: 600; letter-spacing: -0.01em; color: var(--ink); }

.ag-role {
  font-size: 12.5px; line-height: 1.5; color: var(--ink-2); margin-top: 6px;
  display: -webkit-box; -webkit-line-clamp: 2; -webkit-box-orient: vertical; overflow: hidden;
}
.ag-meta { display: flex; align-items: center; gap: 9px; margin-top: 7px; }
.ag-meta em { font-style: normal; font-family: var(--mono); font-size: 9px; color: var(--ink-3); font-variant-numeric: tabular-nums; white-space: nowrap; }
.ag-kids {
  font-family: var(--mono); font-size: 8.5px; color: var(--brass); border: 1px solid rgba(217, 160, 91, 0.28);
  border-radius: 3px; padding: 2px 7px; font-variant-numeric: tabular-nums; text-transform: uppercase; letter-spacing: 0.1em;
}

/* ── the plate face: health · bucket reach · rule count · last report ──────
   Replaces a role line that used to just repeat the name ("Lift Engineer" /
   "Lift Engineer — Engineering"). Four facts, left-aligned, mono, no chrome. */
.ag-facts {
  display: flex; align-items: center; gap: 10px;
  margin-top: 12px; padding-top: 11px; border-top: 1px solid var(--line);
}
.ag-fact { font-style: normal; font-size: 11.5px; font-weight: 600; color: var(--ink-3); }
.ag-fact-health.ok { color: var(--ok); }
.ag-fact-health.warn { color: var(--warn); }
.ag-fact-health.fail { color: var(--fail); }
.ag-fact-health.none { color: var(--ink-3); font-weight: 500; }
.fact-dot { width: 5px; height: 5px; border-radius: 50%; background: var(--ink-3); flex: 0 0 auto; }
.ag-fact-health.ok .fact-dot { background: var(--ok); box-shadow: 0 0 6px rgba(139, 233, 176, 0.75); }
.ag-fact-health.warn .fact-dot { background: var(--brass); box-shadow: 0 0 6px rgba(217, 160, 91, 0.85); }
.ag-fact-health.fail .fact-dot { background: var(--fail); box-shadow: 0 0 7px rgba(224, 123, 106, 0.85); }
.ag-fact-health.ok, .ag-fact-health.warn, .ag-fact-health.fail { color: var(--ink-2); }
.ag-fact-report { margin-left: auto; color: var(--ink-3); font-weight: 400; font-family: var(--mono); font-size: 10px; }

/* "show the law": the boot-order chain, printed on the plate only while the
   toggle is on — the product's core idea, made literal per plate. */
.ag-law { display: none; }
.law-on .ag-law {
  display: block; margin-top: 7px; padding-top: 7px; border-top: 1px dashed rgba(217, 160, 91, 0.32);
  font-family: var(--mono); font-size: 8.5px; letter-spacing: 0.03em; color: var(--brass-hi);
  line-height: 1.6; word-break: break-word;
}
.ag-law-arrow { font-style: normal; color: var(--brass); margin: 0 3px; opacity: 0.85; }
.law-on.ag { box-shadow: 0 0 0 1px rgba(217, 160, 91, 0.3), 0 16px 34px -18px rgba(0, 0, 0, 0.85); }

/* the dossier */
.doss {
  width: 340px; flex: 0 0 340px; border-left: 1px solid var(--line);
  background: var(--bg-1); backdrop-filter: blur(10px);
  padding: 26px 24px 40px; overflow-y: auto; animation: slidein 0.25s ease both;
}
@keyframes slidein { from { opacity: 0; transform: translateX(14px); } to { opacity: 1; transform: none; } }
.doss-head { display: flex; gap: 12px; align-items: center; margin-bottom: 8px; }
.doss-emoji { font-size: 30px; flex: none; }
.doss h2 { margin: 0; font-size: 18px; min-width: 0; }
/* full panel width: a body of four seats is a list, not a subtitle squeezed
   beside three buttons. Middots become the wrap points. */
.doss-role { margin: 0 0 14px; color: var(--ink-2); font-size: 12.5px; line-height: 1.55; }

.doss-chain { font-size: 11px; color: var(--ink-3); margin-bottom: 18px; line-height: 1.7; }
.doss-chain i { font-style: normal; margin: 0 5px; }
.doss-chain b { font-weight: 500; }
.doss-chain b.me { color: var(--accent); font-weight: 650; }

.doss-stats { display: grid; grid-template-columns: repeat(3, 1fr); gap: 8px; margin-bottom: 22px; }
.doss-stat { background: var(--bg-1); border: 1px solid var(--line); border-radius: 11px; padding: 11px 8px; text-align: center; }
.doss-n { font-size: 19px; font-weight: 700; font-variant-numeric: tabular-nums; }
.doss-l { font-size: 9.5px; color: var(--ink-3); margin-top: 3px; text-transform: uppercase; letter-spacing: 0.05em; }

.doss section { margin-bottom: 20px; }
.doss h3 { font-size: 10px; text-transform: uppercase; letter-spacing: 0.09em; color: var(--ink-3); margin: 0 0 9px; }
.doss-empty { color: var(--ink-3); font-size: 12px; margin: 0; }
.doss-rules { list-style: none; margin: 0; padding: 0; display: flex; flex-direction: column; gap: 5px; }
.doss-rules li { font-family: var(--mono); font-size: 11px; color: var(--ink-2); background: var(--bg-1); border: 1px solid var(--line); border-radius: 7px; padding: 6px 9px; word-break: break-all; }
.doss-rules li.own { color: var(--ink); border-color: rgba(79, 184, 160, 0.35); }
.doss-rules em { color: var(--ink-3); font-style: normal; font-size: 9.5px; margin-left: 5px; }
.doss-chips { display: flex; gap: 6px; flex-wrap: wrap; }
.doss-reps { display: flex; flex-direction: column; gap: 7px; }
/* No side-stripe. It was a 2px brass border-left that said nothing the
   status dot doesn't already say properly, and a coloured side-stripe on a
   card is a banned pattern in the house design laws. Full 1px border; the
   whole edge answers on hover. */
.doss-rep {
  background: var(--bg-1); border: 1px solid var(--line);
  border-radius: 9px; padding: 9px 11px; animation: settle 0.35s ease both;
}
.doss-rep-top { display: flex; align-items: baseline; gap: 9px; }
.doss-rep-when { font-size: 10px; color: var(--accent-2); font-variant-numeric: tabular-nums; white-space: nowrap; }
.doss-rep-label { font-size: 12px; font-weight: 600; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.doss-rep-sum { margin: 5px 0 0; font-size: 11.5px; color: var(--ink-2); line-height: 1.55; }
.doss-rep.tap { cursor: pointer; transition: border-color .12s ease, background .12s ease; }
.doss-rep.tap:hover { border-color: var(--accent); background: var(--accent-dim); }
.doss-rep.tap:focus-visible { outline: 2px solid var(--accent); outline-offset: 1px; }
.doss-rep-caret { margin-left: auto; font-size: 10px; color: var(--ink-2); align-self: center; }
.rep-dot { width: 7px; height: 7px; border-radius: 50%; flex: 0 0 auto; align-self: center; }
.rep-dot.ok { background: var(--accent); } .rep-dot.warn { background: var(--warn); } .rep-dot.fail { background: #e07b6a; }
.rep-ok { color: var(--accent); } .rep-warn { color: var(--warn); } .rep-fail { color: #e07b6a; }
.doss-rep-detail { margin-top: 8px; padding-top: 8px; border-top: 1px solid var(--line); font-size: 11px; line-height: 1.7; color: var(--ink-2); font-family: var(--mono); word-break: break-word; }
.doss-rep-detail .doss-l { display: inline-block; min-width: 74px; opacity: .6; text-transform: uppercase; letter-spacing: .04em; font-size: 9.5px; }
.chip { transition: transform .16s var(--ease), background .18s ease; font-size: 11px; background: var(--accent-dim); color: var(--accent-2); border-radius: 7px; padding: 4px 10px; }
.chip.alt { background: var(--bg-2); color: var(--ink-2); }
.doss-boot { font-size: 12px; color: var(--ink-2); line-height: 1.6; margin: 0; white-space: pre-wrap; }
/* contract — one click to open, edit in place, save flows to the org file */
.doss-contract h3 { display: flex; align-items: baseline; gap: 8px; flex-wrap: wrap; }
.contract-card {
  position: relative; display: block; width: 100%; text-align: left; cursor: pointer;
  background: var(--bg-1); border: 1px solid var(--line); border-radius: 12px;
  padding: 13px 14px; transition: border-color 0.15s, box-shadow 0.15s, transform 0.1s;
}
.contract-card:hover { border-color: var(--accent); box-shadow: 0 0 0 3px var(--accent-dim); }
.contract-card:hover .contract-hint { opacity: 1; }
.contract-card.empty { border-style: dashed; }
.contract-hint {
  position: absolute; top: 9px; right: 11px; font-size: 10.5px; font-weight: 650;
  color: var(--accent-2); opacity: 0.55; transition: opacity 0.15s; letter-spacing: 0.02em;
}
.contract-edit { display: flex; flex-direction: column; gap: 8px; }
.contract-ta {
  width: 100%; min-height: 220px; resize: vertical; box-sizing: border-box;
  background: var(--bg-1); border: 1px solid var(--accent); border-radius: 12px;
  padding: 12px 13px; color: var(--ink); font-family: var(--mono); font-size: 12px; line-height: 1.6;
  outline: none; box-shadow: 0 0 0 3px var(--accent-dim);
}
.doss-edit-hint { font-size: 11px; color: var(--ink-3); margin: 2px 0 0; font-style: italic; }
.doss-note { color: var(--ink-3); font-size: 11px; line-height: 1.6; }
.doss-note code { font-family: var(--mono); background: var(--bg-2); padding: 1px 5px; border-radius: 4px; }

.pnl-fatal { min-height: 100vh; display: grid; place-items: center; color: #e07b6a; font-size: 14px; padding: 30px; text-align: center; }
.pnl-fatal.calm { color: var(--ink-2); }

@media (max-width: 760px) {
  /* compact chrome */
  .bar { gap: 8px 14px; padding: 9px 12px; }
  .bar-brand { font-size: 13px; }
  .bar-stats { gap: 11px; font-size: 11px; }
  .bar-stats b { font-size: 12.5px; }
  .bar-actions { gap: 6px; }
  .btn { padding: 6px 11px; font-size: 11.5px; }
  .tabs { padding: 0 4px; }
  .tab { padding: 10px 9px 9px; font-size: 11.5px; }
  .tree { padding: 12px 8px 40px; }
  .tree-hint { display: none; }
  .ag { max-width: 100%; }
  .ag-role { display: none; }
  .screen { padding: 18px 13px 60px; }
  /* the dossier becomes a BOTTOM SHEET inside the pane — the chart above stays
     tappable to switch agents; the ✕ closes. ABSOLUTE (not fixed) so it can
     never overlap an embedding host's chrome. */
  .doss {
    position: absolute; left: 0; right: 0; bottom: 0; top: 34%;
    width: auto; z-index: 6; border-radius: 16px 16px 0 0;
    border-top: 1px solid var(--line);
    box-shadow: 0 -18px 50px rgba(0, 0, 0, 0.55);
  }
  .doss { animation: sheetup 0.25s ease both; }
  @keyframes sheetup { from { opacity: 0; transform: translateY(24px); } to { opacity: 1; transform: none; } }
  .doss-close { display: grid; }
  /* zoom control clears the sheet — top-right of the chart */
  .zoomer { top: 4px; right: 8px; bottom: auto; }
}
`;
